<!DOCTYPE html>
<html lang="en"><head>
<script src="Experiential Learning and Gender Stereotypes - IU_files/libs/clipboard/clipboard.min.js"></script>
<script src="Experiential Learning and Gender Stereotypes - IU_files/libs/quarto-html/tabby.min.js"></script>
<script src="Experiential Learning and Gender Stereotypes - IU_files/libs/quarto-html/popper.min.js"></script>
<script src="Experiential Learning and Gender Stereotypes - IU_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="Experiential Learning and Gender Stereotypes - IU_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Experiential Learning and Gender Stereotypes - IU_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="Experiential Learning and Gender Stereotypes - IU_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <title>experiential-learning-and-gender-stereotypes---iu</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/dist/theme/quarto-5f755d8853ba2267c366030e5f6f86e3.css">
  <link href="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section>
<section id="section" class="title-slide slide level1 center" data-menu-title="Title Slide" style="text-align: left;" data-background-color="#FFFFFF">
<h1></h1>
<div style="margin-left: 20px; margin-top: 20px;">
<h1 style="font-size: 2.75em; margin-top: 0; line-height: 1.1;">
Experiential Learning<br> <span style="font-weight: lighter; color: #555;">&amp; Gender Stereotypes in Science Education</span>
</h1>
<div style="font-size: 0.75em; text-transform: uppercase; letter-spacing: 4px; color: #990000; margin-top: 20px; font-weight: 600;">
<p>Evidence from a Field Intervention</p>
</div>
<p><br></p>
<div style="font-size: 0.8em; color: #333; border-left: 3px solid #990000; padding-left: 15px;">
<p><strong>Presented at:</strong> Kelley Marketing Brown Bag <br> <span style="color: #990000;">April 17, 2026</span></p>
</div>
<div style="font-size: 0.8em; color: #333; border-left: 3px solid #990000; padding-left: 15px;">

</div>
<p><br></p>
<strong>Muzeeb Shaik</strong>
<div style="font-size: 0.8em; color: #990000; margin-bottom: 20px;">
<p>Kelley School of Business | Indiana University, Bloomington</p>
</div>
<div style="font-size: 0.7em; color: #888; margin-bottom: 40px;">
<p><strong>With:</strong> Huanhuan Shi, Adithya Pattabhiramaiah, Hari Sridhar</p>
</div>
</div>
</section>
<section id="the-gender-gap-a-global-pattern" class="slide level2 smaller">
<h2>The Gender Gap: A Global Pattern</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="fragment">
<h3 id="global-picture">Global Picture</h3>
<ul>
<li>Women: only <strong>35%</strong> of STEM graduates worldwide</li>
<li>In the US: <strong>38.8%</strong> of science bachelor’s degrees</li>
<li>Only <strong>26%</strong> of the US STEM workforce</li>
<li><strong>Stakes:</strong> Substantial loss of productive capacity</li>
</ul>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment">
<h3 id="india-our-study-context">India: Our Study Context</h3>
<ul>
<li>Women: <strong>43%</strong> of total undergraduate enrollment</li>
<li>But only <strong>29%</strong> in STEM disciplines</li>
<li>Fewer than <strong>18%</strong> of scientists/engineers in labor force</li>
<li><strong>Opportunity:</strong> Gender parity → <strong>10–12 million</strong> more STEM workers</li>
</ul>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-note no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Today’s Talk</strong></p>
</div>
<div class="callout-content">
<p>What if we could address gender stereotypes <strong>indirectly</strong>, by <strong>redesigning the learning experience itself</strong>?</p>
</div>
</div>
</div>
</div>
</section>
<section id="three-categories-of-prior-interventions" class="slide level2 smaller">
<h2>Three Categories of Prior Interventions</h2>
<div class="columns">
<div class="column" style="width:33%;">
<div class="fragment">
<h3 id="push-campaigns">1. Push Campaigns</h3>
<ul>
<li>Awareness campaigns</li>
<li>Mass communication</li>
<li>Public service announcements</li>
<li>Media messaging</li>
</ul>
<p><strong>Goal:</strong> Persuade individuals to reconsider stereotypes</p>
<p><em>(Paluck et al.&nbsp;2021; Hermann et al.&nbsp;2022)</em></p>
</div>
</div><div class="column" style="width:33%;">
<div class="fragment">
<h3 id="girls-only-programs">2. Girls-Only Programs</h3>
<ul>
<li>After-school STEM activities</li>
<li>Mentoring programs</li>
<li>Interactions with STEM professionals</li>
<li>Separation as confidence-building</li>
</ul>
<p><strong>Goal:</strong> Close information gaps, build exposure</p>
<p><em>(Dubetz &amp; Wilson 2013; Levine et al.&nbsp;2015)</em></p>
</div>
</div><div class="column" style="width:33%;">
<div class="fragment">
<h3 id="gender-congruent-environments">3. Gender-Congruent Environments</h3>
<ul>
<li>Female role models</li>
<li>Feminine classroom décor</li>
<li>Identity-affirming cues</li>
</ul>
<p><strong>Goal:</strong> Counteract masculine coding of science</p>
<p><em>(Master et al.&nbsp;2016; Breda et al.&nbsp;2023)</em></p>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Common Limitation</strong></p>
</div>
<div class="callout-content">
<p>All three approaches <strong>explicitly position gender as the focal problem</strong> and attempt to address it through direct persuasion or identity-targeted messaging</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-problem-with-direct-approaches" class="slide level2 smaller">
<h2>The Problem with Direct Approaches</h2>
<div class="fragment">
<h3 id="these-interventions-risk-reactance">These interventions risk <strong>reactance</strong>:</h3>
</div>
<div class="columns">
<div class="column" style="width:33%;">
<div class="fragment">
<p><strong>Push Campaigns</strong></p>
<ul>
<li>May be dismissed as heavy-handed</li>
<li>Risk appearing tokenizing</li>
<li>Limited lasting impact on beliefs</li>
</ul>
</div>
</div><div class="column" style="width:33%;">
<div class="fragment">
<p><strong>Girls-Only Programs</strong></p>
<ul>
<li>Can <strong>reinforce</strong> the very group boundaries they seek to dismantle</li>
<li>Signal that girls require specialized support</li>
<li>Create parallel tracks rather than inclusive culture</li>
</ul>
</div>
</div><div class="column" style="width:33%;">
<div class="fragment">
<p><strong>Gender-Congruent Cues</strong></p>
<ul>
<li>Signal science requires <strong>special adaptation</strong> for women</li>
<li>Rather than science being a shared, gender-neutral domain</li>
</ul>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Critical Gap</strong></p>
</div>
<div class="callout-content">
<p><strong>None of these approaches engage boys</strong>: the group that holds stronger gender-stereotypical beliefs and whose perceptions shape the social norms defining whether girls feel they belong in science</p>
</div>
</div>
</div>
</div>
</section>
<section id="a-different-approach-indirect-change" class="slide level2 smaller">
<h2>A Different Approach: Indirect Change</h2>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The Approach</strong></p>
</div>
<div class="callout-content">
<p>Rather than <strong>targeting gender perceptions directly</strong>, what if we could produce gender-inclusive outcomes as a <strong>collateral benefit</strong> of redesigning the learning experience itself?</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<h3 id="research-questions">Research Questions</h3>
<p><strong>Primary:</strong> Can experiential science learning, designed for <em>pedagogy</em> not gender, simultaneously improve science knowledge <strong>and</strong> reduce gender stereotypes?</p>
<p><strong>Secondary:</strong></p>
<ul>
<li>Does the intervention affect boys and girls differently?</li>
<li>Do effects extend to broader attitudes about gender and competence?</li>
</ul>
</div>
</section></section>
<section>
<section id="theoretical-framework" class="title-slide slide level1 center">
<h1>Theoretical Framework</h1>

</section>
<section id="how-can-experience-change-perceptions" class="slide level2 smaller">
<h2>How Can Experience Change Perceptions?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="fragment">
<h3 id="marketing-insight-shared-consumption">Marketing Insight: Shared Consumption</h3>
<p>Research shows that <strong>co-consumption</strong> influences:</p>
<ul>
<li>Social perceptions</li>
<li>Norm inference</li>
<li>Identity construction</li>
</ul>
<p><em>(Ramanathan &amp; McGill 2007; Jones &amp; Campbell 2025)</em></p>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment">
<h3 id="belief-updating-mechanism">Belief Updating Mechanism</h3>
<p>When consumers observe others in shared experiences, they <strong>update their beliefs</strong> about:</p>
<ul>
<li>Group capabilities and competencies</li>
<li>Category boundaries and membership</li>
<li>Social norms and expectations</li>
</ul>
</div>
</div></div>
<div style="max-width: 80%; margin: 20px auto 0 auto;">
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Application</strong></p>
</div>
<div class="callout-content">
<p>When science learning is structured as <strong>shared experiential consumption</strong>, cross-gender collaboration triggers <strong>belief updating</strong>:</p>
<ul>
<li>Students observe counter-stereotypical competence firsthand</li>
<li>Direct evidence challenges prior gender-science associations</li>
<li>Shared experience creates common identity around science</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="why-this-should-work-intergroup-contact-theory" class="slide level2 smaller">
<h2>Why This Should Work: Intergroup Contact Theory</h2>
<div class="fragment">
<p><strong>Allport (1954) &amp; Pettigrew &amp; Tropp (2006)</strong></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Core Principle</strong></p>
</div>
<div class="callout-content">
<p>Positive, cooperative interaction between members of different social groups can <strong>reduce prejudice and stereotyping</strong> by fostering understanding and shared identity</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<h3 id="four-optimal-conditions-for-contact">Four Optimal Conditions for Contact</h3>
<div style="white-space: nowrap;">
<ul>
<li><strong>Equal status</strong> between groups in the situation</li>
<li><strong>Common goals</strong> that require interdependence</li>
<li><strong>Intergroup cooperation</strong> (not competition)</li>
<li><strong>Institutional support</strong> from authorities</li>
</ul>
</div>
</div>
<div class="fragment">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Why This Matters</strong></p>
</div>
<div class="callout-content">
<p>When these conditions are met, contact <strong>weakens group boundaries</strong> and promotes more inclusive attitudes, and our intervention creates exactly these conditions</p>
</div>
</div>
</div>
</div>
</section>
<section id="the-delivery-mechanism-experiential-learning" class="slide level2 smaller">
<h2>The Delivery Mechanism: Experiential Learning</h2>
<div class="columns">
<div class="column" style="width:45%;">
<div class="fragment">
<p><strong>Kolb’s Experiential Learning Cycle (1984)</strong></p>
<p><img data-src="images/experiential-learning-cycle.jpg" style="width:80.0%"></p>
</div>
</div><div class="column" style="width:55%;">
<div class="fragment">
<h3 id="theory-of-change">Theory of Change</h3>
<p><strong>Input:</strong> Experiential learning designed for <em>pedagogy</em>, not gender</p>
<p><strong>Mechanism:</strong> Shared experiential consumption triggers <strong>belief updating</strong> through:</p>
<div style="white-space: nowrap;">
<ul>
<li><strong>Joint problem-solving</strong> during experiments</li>
<li><strong>Collaborative sense-making</strong> of results</li>
<li><strong>Equal participation</strong> in learning tasks</li>
</ul>
</div>
<p><strong>Dual Outcomes:</strong> Learning gains (primary goal) AND stereotype reduction (collateral benefit)</p>
</div>
</div></div>
</section>
<section id="what-we-expect-to-find" class="slide level2 smaller">
<h2>What We Expect to Find</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="fragment">
<h3 id="primary-outcome-science-knowledge">Primary Outcome: Science Knowledge</h3>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The Pedagogical Goal</strong></p>
</div>
<div class="callout-content">
<p>Experiential learning will <strong>improve science knowledge</strong> through:</p>
<div style="white-space: nowrap;">
<ul>
<li>Concrete experience with concepts</li>
<li>Reflective observation and discussion</li>
<li>Abstract conceptualization</li>
<li>Active experimentation and application</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment">
<h3 id="added-benefit-reduced-stereotypes">Added Benefit: Reduced Stereotypes</h3>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>The Indirect Effect</strong></p>
</div>
<div class="callout-content">
<p>Shared experiential consumption may <strong>reduce gender-stereotype attitudes</strong> through:</p>
<div style="white-space: nowrap;">
<ul>
<li>Cross-gender contact under optimal conditions</li>
<li>Organic exposure to counterexamples</li>
<li>Weakening of group boundaries</li>
<li>Students experiencing science as “for us”</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div></div>
</section></section>
<section>
<section id="institutional-context" class="title-slide slide level1 center">
<h1>Institutional Context</h1>

</section>
<section id="science-education-in-indian-public-schools" class="slide level2 smaller">
<h2>Science Education in Indian Public Schools</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div style="font-size: 0.78em;">
<h3 id="the-system">The System</h3>
<ul>
<li><strong>70%</strong> of students attend government schools</li>
<li><strong>&gt;50%</strong> of Grades 9–10 learn science <strong>without proper labs</strong></li>
<li>Student-teacher ratios: <strong>20:1 to 27:1</strong></li>
</ul>
<h3 id="pedagogical-approach">Pedagogical Approach</h3>
<ul>
<li><strong>Rote learning</strong> dominates; textbook memorization</li>
<li>Only <strong>14%</strong> of classrooms use non-textbook materials</li>
<li><strong>Gender-segregated seating</strong> (boys on one side, girls on the other)</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Gap</strong></p>
</div>
<div class="callout-content">
<p>Lack of hands-on, interactive learning — and <strong>no cross-gender collaboration</strong>. Exactly where experiential learning could make a difference.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<div style="text-align: center;">
<img data-src="images/traditional_classroom_1.jpeg" class="quarto-figure quarto-figure-center" style="width:80.0%">
<div style="font-size: 0.75em; color: #555; margin-top: 6px;">
A typical public-school classroom: gender-segregated, teacher-centered, no lab.
</div>
</div>
</div></div>
<aside class="notes">
<p><strong>Talking Point:</strong> “Before I show you our intervention, you need to understand the context. In India, 70% of students attend government schools — the backbone of the system. But more than half are learning science without any lab facilities. Combine that with rote learning and 20-to-1 student-teacher ratios, and you have a perfect storm: memorization, zero hands-on experience, and no collaborative inquiry that would create cross-gender contact.”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="study-location-bodoland-assam" class="slide level2 smaller">
<h2>Study Location: Bodoland, Assam</h2>
<div style="font-size: 0.88em;">
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="geographic-context">Geographic Context</h3>
<ul>
<li><strong>Autonomous territorial region</strong> in Northeast India (Assam state)</li>
<li>Established in 2003; Bodo population and other ethnic communities</li>
<li>Complex socio-political environment</li>
</ul>
<h3 id="why-this-location">Why This Location?</h3>
<ul>
<li><strong>Clean baseline</strong> - limited prior exposure to experiential learning</li>
<li><strong>High need</strong> - underserved schools, resource constraints</li>
<li><strong>Scalability insights</strong> - if it works here, it can work anywhere</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="socioeconomic-profile">Socioeconomic Profile</h3>
<ul>
<li>Widespread <strong>socioeconomic disadvantage</strong></li>
<li><strong>Educational underdevelopment</strong> compared to national averages</li>
<li>Predominantly rural population</li>
</ul>
<h3 id="educational-context">Educational Context</h3>
<ul>
<li>Schools operate with minimal facilities</li>
<li>Students have little exposure to hands-on science</li>
<li>Traditional gender norms prevalent</li>
</ul>
</div></div>
</div>
<aside class="notes">
<p><strong>Talking Point:</strong> “We conducted this study in Bodoland, an autonomous region in Northeast India. This isn’t an easy place to work. It’s economically disadvantaged, educationally underdeveloped, and has a complex history of ethnic tensions. But that’s exactly why it’s valuable. These schools have had minimal exposure to educational innovations, so we can cleanly measure our intervention’s impact. And if experiential learning works here, in resource-constrained rural schools with traditional gender norms, then it can work almost anywhere. This is about external validity and policy relevance.”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-intervention" class="title-slide slide level1 center">
<h1>The Intervention</h1>

</section>
<section id="mobile-science-labs-msl-program" class="slide level2 smaller">
<h2>Mobile Science Labs (MSL) Program</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div style="font-size: 0.85em;">
<p><strong>Program Features</strong></p>
<div style="white-space: nowrap;">
<ul>
<li>Vehicles equipped with lab equipment</li>
<li>Two instructors + one driver per MSL</li>
<li>Minimum 2 sessions per day</li>
</ul>
</div>
<p><strong>Implementation</strong></p>
<ul>
<li>10 sessions per academic year + 2 assessment sessions</li>
<li>Subjects: Biology, Chemistry, Physics, and Mathematics</li>
<li>Aligns with <strong>NCERT</strong> and State Board syllabi</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Feature</strong></p>
</div>
<div class="callout-content">
<p><strong>Mixed-gender collaborative activities</strong> — boys and girls working side-by-side on shared experiments.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:45%;">
<div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
<div style="text-align: center; width: 100%;">
<img src="images/msl_vehicle_1.jpeg" style="width: 75%; border-radius: 4px;">
<div style="font-size: 0.75em; color: #555; margin-top: 4px;">
Mobile Science Lab Vehicle
</div>
</div>
<div style="display: flex; gap: 6px; width: 75%; justify-content: center;">
<p><img src="images/hands_on_learning_1.jpeg" style="width: 49%; height: auto; object-fit: contain; border-radius: 4px;"> <img src="images/hands_on_learning_2.jpeg" style="width: 49%; height: auto; object-fit: contain; border-radius: 4px;"></p>
</div>
</div>
</div></div>
</section>
<section id="happening-in-bloomington-too" class="slide level2 smaller">
<h2>Happening in Bloomington Too</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="stem-to-them-mobile-lab">STEM to Them Mobile Lab</h3>
<ul>
<li>Operated by <strong>Monroe County Community School Corporation</strong> with local industry and foundation partners</li>
<li>Brings the same hands-on, vehicle-based science model to Bloomington-area schools</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="text-align: center;">
<img src="images/bloomington_stem_lab.jpg" style="width: 85%; border-radius: 4px;">
<div style="font-size: 0.8em; color: #555; margin-top: 4px;">
<em>STEM to Them</em> mobile lab vehicle in Bloomington, IN.
</div>
</div>
</div></div>
</section></section>
<section>
<section id="research-design" class="title-slide slide level1 center">
<h1>Research Design</h1>

</section>
<section id="study-design-overview" class="slide level2 smaller">
<h2>Study Design Overview</h2>
<div class="columns">
<div class="column" style="width:60%;">
<h3 id="sample-composition">Sample Composition</h3>
<div class="fragment">
<p><strong>Total Sample:</strong></p>
<div style="white-space: nowrap;">
<ul>
<li><strong>N = 5,216 students</strong></li>
<li><strong>193 public schools</strong></li>
<li><strong>Grades 6-8</strong> (middle school)</li>
<li><strong>Location:</strong> Bodoland, Assam, India</li>
</ul>
</div>
</div>
<div class="fragment">
<p><strong>Treatment Group:</strong></p>
<div style="white-space: nowrap;">
<ul>
<li><strong>4,608 students</strong> (88% of sample)</li>
<li>Received MSL intervention</li>
<li>Ten two-hour sessions over the academic year</li>
</ul>
</div>
</div>
<div class="fragment">
<p><strong>Control Group:</strong></p>
<div style="white-space: nowrap;">
<ul>
<li><strong>608 students</strong> (12% of sample)</li>
<li>Regular public school education</li>
<li>No MSL intervention</li>
</ul>
</div>
</div>
</div><div class="column" style="width:40%;">
<h3 id="research-design-1">Research Design</h3>
<div class="fragment">
<p><strong>Design Type:</strong></p>
<ul>
<li><strong>Two-wave panel design</strong></li>
<li>Pre-intervention (baseline)</li>
<li>Post-intervention (endline)</li>
<li><strong>One academic year</strong> duration</li>
</ul>
</div>
<div class="fragment">
<p><strong>Analytical Approach:</strong></p>
<ul>
<li><strong>Difference-in-differences</strong> estimation</li>
<li>School and grade fixed effects (incl.&nbsp;School × Grade)</li>
<li>Clustered standard errors (school level)</li>
<li>Heterogeneity/moderation analyses</li>
</ul>
</div>
</div></div>
<aside class="notes">
<p><strong>Talking Point:</strong> “Now for the research design. We worked with nearly 5,200 students across almost 200 schools in Bodoland. The treatment group (about 4,600 students) received the MSL intervention over one academic year. The control group (about 600 students) continued with regular instruction. We measured outcomes before and after the intervention, which lets us use a difference-in-differences design. This is important because it accounts for any pre-existing differences between treatment and control schools.”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="primary-outcome-measures" class="slide level2 smaller">
<h2>Primary Outcome Measures</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="science-knowledge-score">Science Knowledge Score</h3>
<p><strong>Measurement:</strong></p>
<ul>
<li>4 multiple-choice questions per assessment</li>
<li>Grade-specific content aligned with curriculum</li>
</ul>
<p><strong>Scoring:</strong></p>
<div style="white-space: nowrap;">
<ul>
<li>Percentage of items answered correctly (0-100%)</li>
<li>Enables cross-grade comparison</li>
</ul>
</div>
<p><strong>Validation:</strong></p>
<div style="white-space: nowrap;">
<ul>
<li>Captures applied reasoning (not rote recall)</li>
</ul>
</div>
</div><div class="column" style="width:50%;">
<h3 id="gender-stereotype-attitudes">Gender-Stereotype Attitudes</h3>
<p><strong>Measurement:</strong></p>
<ul>
<li>Single-item: <em>“I feel science is for boys more than girls”</em></li>
<li>5-point Likert scale (1 = Strongly disagree, 5 = Strongly agree)</li>
</ul>
<p><strong>Interpretation:</strong></p>
<div style="white-space: nowrap;">
<ul>
<li>Higher scores = stronger gender stereotypes</li>
</ul>
</div>
<p><strong>Rationale for Single Item:</strong></p>
<ul>
<li>Appropriate for children/adolescents; avoids cognitive overload</li>
<li>Established practice (Deslauriers et al.&nbsp;2019; Carlana et al.&nbsp;2022)</li>
</ul>
</div></div>
<aside class="notes">
<p><strong>Talking Point:</strong> “Our first key outcome is science knowledge. We gave students four multiple-choice questions at the beginning and end of the year. These aren’t memorization questions. They test whether students actually understand scientific concepts and can apply them. We score them as percentage correct, which lets us compare across grades even though the specific questions differ. This measures the pedagogical benefit of experiential learning. Our second key outcome measures gender stereotypes. We asked students directly: ‘I feel science is for boys more than girls.’ Five-point scale from strongly disagree to strongly agree. This is intentionally simple and direct. Some might ask: why just one question? For children, a single clear item is actually better than a long battery of similar questions. It avoids confusion and fatigue while still capturing the core belief we care about: do you think science is gendered or not?”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="secondary-outcomes" class="slide level2 smaller">
<h2>Secondary Outcomes</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="fragment">
<p><strong>Science-Related Attitudes:</strong></p>
<div style="white-space: nowrap;">
<ul>
<li>Interest and enjoyment in science</li>
<li>Science self-efficacy</li>
<li>Long-term science orientation</li>
<li>Intentions to choose science major</li>
<li>14 total constructs measured</li>
</ul>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment">
<p><strong>Gendered Perceptions (Post-intervention only):</strong></p>
<p>Two questions asking students to infer likely gender of a high-performing student:</p>
<ul>
<li><strong>Science domain:</strong> “A student performs very well in science. Is this student a boy or a girl?”</li>
<li><strong>Language arts domain:</strong> “A student performs very well in language arts. Is this student a boy or a girl?”</li>
</ul>
</div>
</div></div>
<!-- ## Outcome Measures -->
<!-- ### Design Strength -->
<!-- ::: {.callout-tip} -->
<!-- ## Causal Identification -->
<!-- - Random assignment at school level -->
<!-- - Pre differences accounted for -->
<!-- - Multiple fixed effects specifications -->
<!-- - Robust standard errors (school clusters) -->
<!-- - Large sample size -->
<!-- ::: -->
<!-- ## Analytical Strategy {.smaller} -->
<!-- ::: fragment -->
<!-- ### Difference-in-Differences Framework -->
<!-- **Base specification:** -->
<!-- $Y_{ist} = \beta_0 + \beta_1 Treatment_s + \beta_2 Post_t + \beta_3 (Treatment_s \times Post_t) + \varepsilon_{ist}$ -->
<!-- Where: -->
<!-- -   $Y_{ist}$ = outcome for student $i$ in school $s$ at time $t$ -->
<!-- -   $Treatment_s$ = indicator for treatment school -->
<!-- -   $Post_t$ = indicator for post-intervention period -->
<!-- ::: -->
<!-- ::: fragment -->
<!-- ### What Each Term Captures -->
<!-- -   $\beta_1$ (Treatment): Baseline difference between treatment and -->
<!--     control -->
<!-- -   $\beta_2$ (Post): Time trend (change in control group) -->
<!-- -   $\beta_3$ (Treatment × Post): Additional change in treatment group -->
<!--     beyond the control group = **CAUSAL EFFECT** -->
<!-- ::: -->
</section></section>
<section>
<section id="results" class="title-slide slide level1 center">
<h1>Results</h1>

</section>
<section id="model-free-evidence" class="slide level2 smaller">
<h2>Model-Free Evidence</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="science-knowledge">Science Knowledge</h3>
<p><img data-src="images/Science%20Knowledge%20Score%20Bodoland.png" style="width:95.0%"></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Catch-up Effect:</strong> Treatment started lower (16%) but overtook Control (29%) by endline — the initial gap closed.</p>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<h3 id="gender-stereotypes">Gender Stereotypes</h3>
<p><img data-src="images/Gender%20Stereotype%20Attitudes%20Bodoland.png" style="width:95.0%"></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Control attitudes <strong>remained stable</strong>; the intervention significantly reduced <em>“science is for boys”</em> beliefs.</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="regression-results" class="slide level2 smaller">
<h2>Regression Results</h2>
<div class="columns">
<div class="column" style="width:78%;">
<h3 id="difference-in-differences-estimates">Difference-in-Differences Estimates</h3>
<div style="font-size: 0.75em;">
<p style="text-align: center;">
<em>Panel A: Science Knowledge Score</em>
</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Model 1</th>
<th>Model 2</th>
<th>Model 3</th>
<th>Model 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>No FE</td>
<td>School FE</td>
<td>School + Grade FE</td>
<td>School × Grade FE</td>
</tr>
<tr class="even">
<td><span class="my-crimson"><strong>Treatment × Post</strong></span></td>
<td><span class="my-crimson"><strong>13.763</strong>*</span></td>
<td><span class="my-crimson"><strong>13.763</strong>*</span></td>
<td><span class="my-crimson"><strong>13.763</strong>*</span></td>
<td><span class="my-crimson"><strong>13.763</strong>*</span></td>
</tr>
<tr class="odd">
<td></td>
<td>(2.743)</td>
<td>(2.743)</td>
<td>(2.747)</td>
<td>(2.743)</td>
</tr>
<tr class="even">
<td></td>
<td>p&lt;.001</td>
<td>p&lt;.001</td>
<td>p&lt;.001</td>
<td>p&lt;.001</td>
</tr>
<tr class="odd">
<td>N</td>
<td>10,432</td>
<td>10,432</td>
<td>10,432</td>
<td>10,432</td>
</tr>
<tr class="even">
<td>R²</td>
<td>.076</td>
<td>.255</td>
<td>.317</td>
<td>.398</td>
</tr>
</tbody>
</table>
<div style="font-size: 0.9em;">
<p style="text-align: center;">
<em>Panel B: Gender-Stereotype Attitudes</em>
</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Model 1</th>
<th>Model 2</th>
<th>Model 3</th>
<th>Model 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>No FE</td>
<td>School FE</td>
<td>School + Grade FE</td>
<td>School × Grade FE</td>
</tr>
<tr class="even">
<td><span class="my-crimson"><strong>Treatment × Post</strong></span></td>
<td><span class="my-crimson"><strong>-0.595</strong>**</span></td>
<td><span class="my-crimson"><strong>-0.576</strong>**</span></td>
<td><span class="my-crimson"><strong>-0.575</strong>**</span></td>
<td><span class="my-crimson"><strong>-0.573</strong>**</span></td>
</tr>
<tr class="odd">
<td></td>
<td>(0.186)</td>
<td>(0.188)</td>
<td>(0.188)</td>
<td>(0.188)</td>
</tr>
<tr class="even">
<td></td>
<td>p=.002</td>
<td>p=.003</td>
<td>p=.003</td>
<td>p=.003</td>
</tr>
<tr class="odd">
<td>N</td>
<td>10,214</td>
<td>10,214</td>
<td>10,214</td>
<td>10,214</td>
</tr>
<tr class="even">
<td>R²</td>
<td>.061</td>
<td>.205</td>
<td>.207</td>
<td>.236</td>
</tr>
</tbody>
</table>
<p style="text-align: center;">
<em>Standard errors clustered at school level</em>
</p>
</div>
</div>
</div><div class="column" style="width:22%;">
<div class="r-stack">
<div class="fragment fade-in-then-out" data-fragment-index="1">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Science Knowledge Score</strong></p>
</div>
<div class="callout-content">
<p><strong>Effect: +13.8 pts</strong></p>
<p>88% improvement over baseline</p>
<p>Consistent across all 4 specifications</p>
</div>
</div>
</div>
</div>
<div class="fragment" data-fragment-index="2">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Gender-Stereotype Attitudes</strong></p>
</div>
<div class="callout-content">
<p><strong>Effect: -0.58 pts</strong></p>
<p>~20% reduction from baseline</p>
<p>Robust to all controls</p>
</div>
</div>
</div>
</div>
</div>
</div></div>
</section>
<section id="moderation-by-student-gender" class="slide level2 smaller">
<h2>Moderation by Student Gender</h2>
<div class="columns">
<div class="column" style="width:68%;">
<h3 id="regression-results-1">Regression Results</h3>
<div class="smaller">
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Science Knowledge Score</th>
<th></th>
<th>Gender-Stereotype Attitudes</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Coef. (S.E.)</td>
<td>p-value</td>
<td>Coef. (S.E.)</td>
<td>p-value</td>
</tr>
<tr class="even">
<td><span class="my-crimson"><strong>Treatment × Post × Male</strong></span></td>
<td>0.642 (3.096)</td>
<td>.836</td>
<td><span class="my-crimson"><strong>-0.658 (0.213)</strong></span></td>
<td><span class="my-crimson"><strong>.002</strong></span></td>
</tr>
<tr class="odd">
<td>Treatment × Post</td>
<td>13.505 (3.165)</td>
<td>&lt;.001</td>
<td>-0.290 (0.217)</td>
<td>.183</td>
</tr>
<tr class="even">
<td>Treatment × Male</td>
<td>1.811 (2.235)</td>
<td>.417</td>
<td>0.287 (0.131)</td>
<td>.030</td>
</tr>
<tr class="odd">
<td>Post × Male</td>
<td>-1.275 (2.941)</td>
<td>.665</td>
<td>0.524 (0.203)</td>
<td>.011</td>
</tr>
<tr class="even">
<td>Male</td>
<td>-2.324 (2.147)</td>
<td>.280</td>
<td>-0.071 (0.120)</td>
<td>.558</td>
</tr>
<tr class="odd">
<td>Post</td>
<td>-0.359 (2.964)</td>
<td>.904</td>
<td>-0.316 (0.199)</td>
<td>.114</td>
</tr>
<tr class="even">
<td><strong>N</strong></td>
<td>10,432</td>
<td></td>
<td>10,214</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>R²</strong></td>
<td>.379</td>
<td></td>
<td>.240</td>
<td></td>
</tr>
</tbody>
</table>
<p><em>School × Grade fixed effects; Standard errors clustered at school level</em></p>
</div>
</div><div class="column" style="width:22%;">
<div class="r-stack">
<div class="fragment fade-in-then-out" data-fragment-index="1">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Science Knowledge Score</strong></p>
</div>
<div class="callout-content">
<p><strong>p = .836</strong></p>
<p>NOT significant</p>
<p>Equal gains for boys and girls (~14 pts)</p>
</div>
</div>
</div>
</div>
<div class="fragment" data-fragment-index="2">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Gender-Stereotype Attitudes</strong></p>
</div>
<div class="callout-content">
<p><strong>p = .002</strong></p>
<p>Significant</p>
<p>Boys: 3× larger reduction compared to girls</p>
</div>
</div>
</div>
</div>
</div>
</div></div>
</section>
<section id="why-bigger-effects-for-boys" class="slide level2 smaller">
<h2>Why Bigger Effects for Boys?</h2>
<ul>
<li class="fragment"><strong>Higher baseline bias</strong> → More room for belief updating</li>
<li class="fragment"><strong>Firsthand observation</strong> of girls’ competence during shared consumption</li>
<li class="fragment"><strong>Belief updating</strong> when direct evidence contradicts prior stereotypes</li>
<li class="fragment"><strong>Inter-group contact theory</strong> prediction confirmed</li>
</ul>
</section>
<section id="broader-science-attitudes-multifaceted-spillovers" class="slide level2 smaller">
<h2>Broader Science Attitudes: Multifaceted Spillovers</h2>
<div class="columns">
<div class="column" style="width:42%;">
<h3 id="beyond-primary-outcomes">Beyond Primary Outcomes</h3>
<p>We measured <strong>14 additional constructs</strong> across four categories:</p>
<ul>
<li><strong>Interest &amp; Enjoyment</strong> (3 items)</li>
<li><strong>Self-Efficacy</strong> (4 items)</li>
<li><strong>Long-Term Orientation</strong> (4 items)</li>
<li><strong>Perceived Value</strong> (3 items)</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Multifaceted Impact</strong></p>
</div>
<div class="callout-content">
<p>Positive effects on <strong>12 of 14 outcomes</strong> — the intervention shifts the broader constellation of science attitudes, not only knowledge and stereotypes.</p>
</div>
</div>
</div>
</div><div class="column" style="width:58%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/forest_plot_science_related.png" class="quarto-figure quarto-figure-center" style="width:85.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="perceptions-of-academic-excellence" class="slide level2 smaller">
<h2>Perceptions of Academic Excellence</h2>
<div style="text-align: center; color: #555; margin-bottom: 18px;">
<p><em>“A student performs very well in [science / language arts]. Is this student a boy or a girl?”</em></p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="science-excellence">Science Excellence</h3>
<p><span class="my-crimson"><strong>β = 0.55</strong>*</span> — treated students are less likely to assume “boy”; more “could be either” responses.</p>
</div><div class="column" style="width:50%;">
<h3 id="language-arts-excellence">Language Arts Excellence</h3>
<p><span class="my-crimson"><strong>β = 0.45</strong>*</span> — same pattern carries over to a non-science domain.</p>
</div></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Treated students attribute academic excellence <strong>more equally across genders</strong>, with effects strongest in the targeted science domain.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="exploring-the-mechanism" class="title-slide slide level1 center" data-section="mechanism">
<h1>Exploring the Mechanism</h1>

</section>
<section id="why-we-need-more-than-field-evidence" class="slide level2 smaller">
<h2>Why We Need More Than Field Evidence</h2>
<div class="columns">
<div class="column" style="width:55%;">
<h3 id="the-field-study-bundles-multiple-features">The field study bundles multiple features</h3>
<p>The MSL program combines:</p>
<ul>
<li>Experiential, hands-on pedagogy</li>
<li><strong>Mixed-gender</strong> collaborative grouping</li>
<li>Equal-status peer interaction</li>
<li>Extended exposure over several sessions</li>
</ul>
<p>The field data <strong>cannot isolate</strong> whether stereotype reduction arises from the gender composition of groups, the hands-on nature of activities, or some combination.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two randomized studies</strong></p>
</div>
<div class="callout-content">
<p><strong>1. Scenario Experiment</strong></p>
<p>N = 151 US adults on Prolific. Comic-strip vignettes that manipulate the gender composition of a science task.</p>
<p><strong>2. Synthetic Participant Replication </strong></p>
<p>450 LLM agent surrogates with demographically diverse personas — does the pattern hold under a very different participant source?</p>
</div>
</div>
</div>
</div></div>
</section>
<section id="scenario-experiment-design" class="slide level2 smaller scrollable">
<h2>Scenario Experiment: Design</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="between-subjects-3-conditions">Between-subjects, 3 conditions</h3>
<div style="background: rgba(153,0,0,0.06); border-radius: 8px; padding: 15px; margin-top: 10px; border-left: 4px solid #990000;">
<p><strong>Mixed-Gender</strong> — Emily &amp; Jake collaborate equally on the experiment</p>
<p><strong>Solo-Male</strong> — Jake conducts the experiment alone</p>
<p><strong>Solo-Female</strong> — Emily conducts the experiment alone</p>
</div>
<p><br></p>
<ul>
<li><strong>Stimulus</strong>: comic-strip vignettes of a chemistry experiment on how temperature affects reaction rate</li>
<li><strong>Identical</strong> in content, visual style, and length; differ <strong>only</strong> in gender composition</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="sample-and-measures">Sample and measures</h3>
<ul>
<li><strong>N = 151</strong> adults aged 18-30, US residents (Prolific)</li>
<li>59.6% female, 37.1% male, 3.3% non-binary</li>
<li>Approximately balanced across conditions (n ≈ 50 each)</li>
<li>100% passed both attention-check questions</li>
</ul>
<h3 id="outcome">Outcome</h3>
<p>Composite of <strong>four stereotype items</strong> on a 5-pt Likert scale (α = .845):</p>
<ol type="1">
<li><em>“Boys are naturally better at science than girls”</em></li>
<li><em>“Science is more of a ‘boy thing’ than a ‘girl thing’”</em></li>
<li><em>“Girls can be just as good at science as boys”</em> (reverse-coded)</li>
<li><em>“Boys tend to be more interested in science than girls”</em></li>
</ol>
</div></div>
</section>
<section id="scenario-experiment-the-three-stimuli" class="slide level2 smaller">
<h2>Scenario Experiment: The Three Stimuli</h2>
<div style="display: flex; justify-content: center; gap: 18px; margin-top: 10px;">
<div style="width: 480px; text-align: center;">
<div style="font-weight: bold; color: #990000; margin-bottom: 6px; font-size: 0.95em;">
Mixed-Gender (Emily &amp; Jake)
</div>
<p><img src="images/scenario_stimulus_mixed_gender.png" width="480" height="320" style="display: block; width: 480px; height: auto; border: 1px solid #ccc; border-radius: 6px;"></p>
</div>
<div style="width: 480px; text-align: center;">
<div style="font-weight: bold; color: #990000; margin-bottom: 6px; font-size: 0.95em;">
Solo-Male (Jake)
</div>
<p><img src="images/scenario_stimulus_solo_male.png" width="480" height="320" style="display: block; width: 480px; height: auto; border: 1px solid #ccc; border-radius: 6px;"></p>
</div>
<div style="width: 480px; text-align: center;">
<div style="font-weight: bold; color: #990000; margin-bottom: 6px; font-size: 0.95em;">
Solo-Female (Emily)
</div>
<p><img src="images/scenario_stimulus_solo_female.png" width="480" height="320" style="display: block; width: 480px; height: auto; border: 1px solid #ccc; border-radius: 6px;"></p>
</div>
</div>
<div style="font-size: 0.8em; color: #555; margin-top: 14px; text-align: center; max-width: 1200px; margin-left: auto; margin-right: auto;">
<p>All three vignettes depict the same chemistry experiment — temperature effects on reaction rate — with identical dialogue content; only the gender composition of the protagonists varies.</p>
</div>
</section>
<section id="scenario-experiment-results" class="slide level2 smaller">
<h2>Scenario Experiment: Results</h2>
<div style="text-align: center;">
<p><img src="images/scenario_experiment_bar.png" style="width: 56%; max-width: 900px;"></p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Contact beyond role models</strong></p>
</div>
<div class="callout-content">
<p>Among <strong>female participants</strong>, Mixed-Gender (M = 1.31) scored <strong>below Solo-Female</strong> (M = 1.49) — contact reduces stereotypes <strong>above and beyond</strong> counter-stereotypical exemplars (d = −0.63, p = .021).</p>
</div>
</div>
</div>
</section>
<section id="synthetic-participant-replication-setup" class="slide level2 smaller">
<h2>Synthetic Participant Replication: Setup</h2>
<h3 id="llm-agent-surrogates-150-per-condition">450 LLM agent surrogates (150 per condition)</h3>
<p>Building on the <strong>homo silicus</strong> framework (Horton 2023) and recent marketing work on GenAI-assisted research (Arora et al.&nbsp;2025; Blanchard et al.&nbsp;2025).</p>
<div class="columns">
<div class="column" style="width:50%;">
<div title="Design">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Design</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>Model:</strong> Claude Sonnet API (fixed version, controlled temperature)</li>
<li><strong>Personas:</strong> each agent varies in age, gender, race, academic major, and science attitudes</li>
<li><strong>Stimuli:</strong> text-based versions of the same three vignettes</li>
</ul>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div title="Two notable differences vs. human study">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two notable differences vs.&nbsp;human study</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Stereotype items use <strong>projective framing</strong> to reduce social-desirability bias (Luchs et al.&nbsp;2010)</li>
<li>Vignettes delivered as <strong>text</strong>, not comic strips (API-based execution)</li>
</ul>
</div>
</div>
</div>
</div>
</div></div>
</section>
<section id="synthetic-participant-replication-results" class="slide level2 smaller">
<h2>Synthetic Participant Replication: Results</h2>
<div style="text-align: center;">
<p><img src="images/edsl_synthetic_bar.png" style="width: 56%; max-width: 900px;"></p>
</div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Same pattern across participant sources</strong></p>
</div>
<div class="callout-content">
<p>The Mixed-Gender &lt; Solo-Male ordering replicates with 450 LLM agents (d = 0.65, p &lt; .001). Treat this as a <strong>directional robustness check</strong>, not independent causal evidence — LLM agents may reflect training-data regularities rather than genuine psychological processes.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="discussion" class="title-slide slide level1 center" data-section="implications">
<h1>Discussion</h1>

</section>
<section id="theoretical-contributions" class="slide level2 smaller">
<h2>Theoretical Contributions</h2>
<div class="columns">
<div class="column" style="width:33%;">
<h3 id="marketing-theory">Marketing theory</h3>
<ul>
<li>Extends <strong>shared consumption</strong> and <strong>social learning</strong> from commercial to educational settings</li>
<li>Frames belief change as <strong>symbolic brand repositioning</strong> — who belongs in a domain</li>
<li>Experience-based, not persuasion-based, identity change</li>
</ul>
</div><div class="column" style="width:33%;">
<h3 id="education-gender-equity">Education &amp; gender equity</h3>
<ul>
<li>Spotlights <strong>boys and peer environments</strong> as central levers for stereotype reduction</li>
<li>Complements a literature focused on interventions targeting girls</li>
<li>Boys who update their beliefs grow into male teachers, managers, and colleagues</li>
</ul>
</div><div class="column" style="width:33%;">
<h3 id="service-design">Service design</h3>
<ul>
<li><strong>Indirect change</strong> as a design principle: redesign the <em>experience</em>, not the <em>message</em></li>
<li>Dual-outcome design (knowledge + attitudes) from a single program</li>
<li>Equal-status, mixed-gender collaboration as a replicable service feature</li>
</ul>
</div></div>
</section>
<section id="policy-implications" class="slide level2 smaller">
<h2>Policy Implications</h2>
<div class="columns">
<div class="column" style="width:33%;">
<h3 id="for-ngos-policymakers">For NGOs &amp; policymakers</h3>
<ul>
<li>Experiential learning is a <strong>scalable lever</strong> — no identity-targeted programming needed</li>
<li>Investment in lab access + facilitator training has <strong>dual returns</strong></li>
<li>Works across class compositions (no ratio engineering required)</li>
</ul>
</div><div class="column" style="width:33%;">
<h3 id="for-corporate-funders">For corporate funders</h3>
<ul>
<li>High-leverage CSR channel: one program delivers <strong>education outcomes</strong> <em>and</em> <strong>gender equity</strong> KPIs</li>
<li>Metrics align with UN SDG reporting</li>
<li>Measurable downstream impact on the STEM pipeline</li>
</ul>
</div><div class="column" style="width:33%;">
<h3 id="for-school-leaders">For school leaders</h3>
<ul>
<li><strong>Pedagogy is the intervention</strong> — everyday classroom design choices matter</li>
<li>Mixed-gender grouping on shared tasks is <strong>low-cost, high-signal</strong></li>
<li>Gains are larger in <strong>larger schools</strong> where norms are most salient</li>
</ul>
</div></div>
</section>
<section id="alignment-with-un-sdgs" class="slide level2 smaller">
<h2>Alignment with UN SDGs</h2>
<div class="columns">
<div class="column" style="width:45%;">
<p><img data-src="images/SDG.png" style="width:90.0%"></p>
</div><div class="column" style="width:55%;">
<h3 id="sdg-4-quality-education">SDG 4 — Quality Education</h3>
<ul>
<li>Hands-on, experiential science instruction</li>
<li>Measurable improvement in standardized knowledge</li>
</ul>
<h3 id="sdg-5-gender-equality">SDG 5 — Gender Equality</h3>
<ul>
<li>Stereotype reductions during formative years</li>
<li>Reshaping who belongs in science upstream of the STEM pipeline leak</li>
</ul>
<p><strong>A single service-design intervention advances two SDGs simultaneously</strong> — dual-impact evidence donors and multilateral agencies look for.</p>
</div></div>
</section>
<section id="thank-you" class="slide level2 center" data-background-color="#FFFFFF">
<h2>Thank You</h2>
<div style="font-size: 1.5em; color: #555; margin-top: 20px;">
<p>Questions &amp; Comments?</p>
</div>
<hr style="border-top: 3px solid #990000; width: 100px; margin: 20px 0;">
<div style="font-size: 1.2em; font-weight: bold;">
<p>Muzeeb Shaik</p>
</div>
<div style="font-size: 0.8em; color: gray;">
Assistant Professor
</div>
<div style="font-size: 0.8em; color: gray;">
Kelley School of Business
</div>
<div style="font-size: 0.8em; color: gray;">
Indiana University - Bloomington
</div>
<div style="margin-top: 10px;">
<p><a href="mailto:shaikmu@iu.edu" style="font-size: 0.8em; color: #990000; text-decoration: none; font-weight: bold;">shaikmu@iu.edu</a></p>
</div>
</section></section>
<section>
<section id="appendix" class="title-slide slide level1 center" data-visibility="uncounted">
<h1>Appendix</h1>

</section>
<section id="field-study-primary-outcome-measures" class="slide level2 smaller" data-visibility="uncounted">
<h2>Field Study — Primary Outcome Measures</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="gender-stereotype-attitude-primary-attitudinal-outcome">Gender-Stereotype Attitude (primary attitudinal outcome)</h3>
<p>Single-item measure administered at baseline and endline:</p>
<blockquote>
<p><strong>“I feel science is for boys more than girls.”</strong></p>
</blockquote>
<ul>
<li>5-point Likert scale</li>
<li>1 = Strongly Disagree · · · 5 = Strongly Agree</li>
<li>Higher scores = stronger stereotype endorsement</li>
<li>N = 10,214 students with complete responses across two waves</li>
</ul>
<p><em>Item is a concrete, single-referent belief — the type of construct for which single-item measurement is appropriate (Bergkvist &amp; Rossiter 2007).</em></p>
</div><div class="column" style="width:50%;">
<h3 id="science-knowledge-score-3">Science Knowledge Score</h3>
<ul>
<li>Standardized, grade-appropriate science test</li>
<li>Covers chemistry, physics, and biology content aligned with the state curriculum</li>
<li>Scored as a percentage correct</li>
<li>N = 10,432 students with complete responses across two waves</li>
<li>Administered at baseline (pre-intervention) and endline (post-intervention)</li>
</ul>
</div></div>
</section>
<section id="field-study-broader-science-attitudes-secondary" class="slide level2 smaller" data-visibility="uncounted">
<h2>Field Study — Broader Science Attitudes (Secondary)</h2>
<h3 id="items-across-four-conceptual-categories">14 items across four conceptual categories</h3>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>1. Interest &amp; enjoyment of science</strong></p>
<ul>
<li>I enjoy doing science activities</li>
<li>Science is one of my favorite subjects</li>
<li>I look forward to science class</li>
<li>I find science interesting</li>
</ul>
<p><strong>2. Self-efficacy in science</strong></p>
<ul>
<li>I feel confident solving science problems</li>
<li>I can understand difficult science concepts</li>
<li>I am good at science</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>3. Career intentions in STEM</strong></p>
<ul>
<li>I want to have a career that uses science</li>
<li>I would like to be a scientist / engineer / doctor</li>
<li>I can picture myself working in a science field</li>
</ul>
<p><strong>4. Perceived social value of science</strong></p>
<ul>
<li>Science helps solve important problems</li>
<li>My community values science</li>
<li>Science is useful in everyday life</li>
<li>Understanding science helps me make good decisions</li>
</ul>
<p><em>All items: 5-pt Likert (1 = strongly disagree, 5 = strongly agree).</em></p>
</div></div>
</section>
<section id="field-study-gendered-perception-of-academic-excellence" class="slide level2 smaller" data-visibility="uncounted">
<h2>Field Study — Gendered Perception of Academic Excellence</h2>
<h3 id="projective-style-post-intervention-item">Projective-style post-intervention item</h3>
<p>Respondents were asked, for each of two domains:</p>
<blockquote>
<p><strong>“A student performs very well in [science / language arts]. Is this student a boy or a girl?”</strong></p>
</blockquote>
<ul>
<li>Response options: <strong>Boy</strong> · <strong>Girl</strong> · <strong>Could be either</strong></li>
<li>Administered separately for <strong>science</strong> excellence and <strong>language arts</strong> excellence</li>
<li>Outcome coded to capture share of students attributing excellence <strong>more equally across genders</strong> (“could be either” or balanced responses)</li>
<li>Language-arts version serves as a <strong>placebo check</strong> — does the intervention shift gender attributions only in the targeted domain?</li>
</ul>
</section>
<section id="robustness-check-cem-matching" class="slide level2 smaller" data-visibility="uncounted">
<h2>Robustness Check: CEM Matching</h2>
<p><strong>Addressing Baseline Differences in Science Knowledge</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="fragment" data-fragment-index="1">
<p><strong>Pre-Match Balance:</strong></p>
<ul>
<li>Treatment: 15.87%</li>
<li>Control: 26.27%</li>
<li>Std. Mean Diff: -0.64</li>
</ul>
</div>
<div class="fragment" data-fragment-index="2">
<p><strong>Post-Match Balance:</strong></p>
<ul>
<li>Both: 15.87%</li>
<li>Std. Mean Diff: 0.00</li>
<li>Perfect balance achieved</li>
</ul>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment" data-fragment-index="3">
<p><strong>CEM-Weighted Results:</strong></p>
<ul>
<li>Treatment × Post: 4.62†</li>
<li>(SE = 2.37, p = .053)</li>
<li>Confirms robustness</li>
</ul>
</div>
<div class="fragment" data-fragment-index="4">
<p>✓ Results hold after controlling for baseline proficiency</p>
</div>
</div></div>
</section>
<section id="scenario-experiment-stereotype-composite" class="slide level2 smaller scrollable" data-visibility="uncounted">
<h2>Scenario Experiment — Stereotype Composite</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="four-items-5-pt-likert-α-.845">Four items (5-pt Likert; α = .845)</h3>
<ol type="1">
<li><em>“Boys are naturally better at science than girls.”</em></li>
<li><em>“Science is more of a ‘boy thing’ than a ‘girl thing.’”</em></li>
<li><em>“Girls can be just as good at science as boys.”</em> <strong>(reverse-coded)</strong></li>
<li><em>“Boys tend to be more interested in science than girls.”</em></li>
</ol>
<p>Scoring:</p>
<ul>
<li>Scale: 1 = Strongly Disagree · · · 5 = Strongly Agree</li>
<li>Item 3 reverse-coded; then all four averaged into a composite</li>
<li>Higher composite = stronger stereotype endorsement</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="sample-procedure">Sample &amp; procedure</h3>
<ul>
<li><strong>N = 151</strong> adults aged 18–30 recruited on <strong>Prolific</strong></li>
<li>US residents with at least secondary education</li>
<li>59.6% female, 37.1% male, 3.3% non-binary</li>
<li>Approximately balanced across 3 conditions (n ≈ 50 each)</li>
<li>Participants viewed one of three comic-strip vignettes (Mixed-Gender / Solo-Male / Solo-Female), then completed two attention checks before the stereotype items</li>
</ul>
</div></div>
</section>
<section id="scenario-experiment-attention-checks" class="slide level2 smaller" data-visibility="uncounted">
<h2>Scenario Experiment — Attention Checks</h2>
<h3 id="two-comprehension-checks-verifying-the-vignette-was-processed">Two comprehension checks verifying the vignette was processed</h3>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Attention Check 1</strong></p>
<blockquote>
<p><strong>“In the comic strip you just saw, what were the student(s) doing?”</strong></p>
</blockquote>
<ul>
<li>A math problem</li>
<li>Reading a book</li>
<li><strong>A chemistry experiment</strong> ← correct</li>
<li>Playing a sport</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Attention Check 2</strong></p>
<blockquote>
<p><strong>“In the comic strip you just saw, who was/were the main character(s)?”</strong></p>
</blockquote>
<ul>
<li>Condition-appropriate names (Emily, Jake, or both) as the correct option, with foils</li>
</ul>
</div></div>
<p><br></p>
<ul>
<li><strong>100% pass rate</strong> on both checks across all three conditions</li>
<li>Stereotype items administered only after both attention checks</li>
<li>Stimuli reproduced in <strong>Web Appendix G</strong> of the paper</li>
</ul>
</section>
<section id="edsl-synthetic-replication-agent-construction" class="slide level2 smaller" data-visibility="uncounted">
<h2>EDSL Synthetic Replication — Agent Construction</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="persona-dimensions-each-agent-unique">Persona dimensions (each agent unique)</h3>
<ul>
<li><strong>Age</strong> (18–30 distribution matching Prolific sample)</li>
<li><strong>Gender</strong> (balanced across male, female, non-binary)</li>
<li><strong>Race/ethnicity</strong> (US census-matched distribution)</li>
<li><strong>Academic major</strong> (STEM / non-STEM / undeclared)</li>
<li><strong>Baseline science attitudes</strong> (low / moderate / high)</li>
</ul>
<h3 id="stimuli">Stimuli</h3>
<ul>
<li><strong>Text-based</strong> descriptions of the same three conditions (Mixed-Gender / Solo-Male / Solo-Female)</li>
<li>Vignette text parallels the comic-strip dialogue</li>
<li>Each agent assigned to one condition (150 per condition, N = 450)</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="execution-best-practices-blanchard-et-al.-2025">Execution best practices (Blanchard et al.&nbsp;2025)</h3>
<ul>
<li><strong>Model:</strong> Claude Sonnet via Anthropic API</li>
<li>API-based execution (not chat interface)</li>
<li><strong>Fixed model version</strong></li>
<li><strong>Temperature controlled</strong></li>
<li>Complete response logging (including agent-generated open-ended reasoning)</li>
</ul>
<h3 id="item-framing-difference-vs.-human-study">Item framing difference vs.&nbsp;human study</h3>
<ul>
<li>Stereotype items delivered with <strong>projective framing</strong> (third-person phrasing; Luchs et al.&nbsp;2010) to reduce social-desirability bias in LLM responses</li>
<li>Otherwise item content mirrors the human scenario experiment</li>
</ul>
</div></div>
<div style="font-size: 0.8em; color: #555; margin-top: 14px;">
<p>Full methodology in Web Appendix H of the paper.</p>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/kelley-marketing-revised-removebg-preview.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="Experiential Learning and Gender Stereotypes - IU_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>